import type { ProfileToMdOptions } from '../../common.ts'
import { normalizeSpeedscopeToMdOptions } from './common.ts'
import { formatSpeedscope } from './format.ts'
import { parseSpeedscopeProfile } from './parse.ts'
import type { SpeedscopeProfile } from './parse.ts'
import { summarizeSpeedscopeProfile } from './summarize.ts'

export const detectSpeedscopeProfile = (
  json: unknown,
): SpeedscopeProfile | undefined => {
  if (typeof json !== `object` || json === null) {
    return undefined
  }

  const object = json as Record<string, unknown>
  if (
    object.$schema !== `https://www.speedscope.app/file-format-schema.json` ||
    !Array.isArray(object.profiles) ||
    typeof object.shared !== `object` ||
    object.shared === null
  ) {
    return undefined
  }

  return json as SpeedscopeProfile
}

/**
 * Converts the given speedscope profile to Markdown.
 *
 * It is assumed that {@link data} is a valid speedscope JSON file. The behavior
 * of this function is undefined for invalid profiles.
 *
 * Speedscope profiles can be generated by many tools, including:
 * - [speedscope](https://www.speedscope.app) (drag and drop any supported profile)
 * - [rbspy](https://rbspy.github.io) for Ruby
 * - [py-spy](https://github.com/benfred/py-spy) for Python (`--format speedscope`)
 * - [pprof-rs](https://github.com/tikv/pprof-rs) for Rust
 */
export const speedscopeProfileToMd = (
  data: string | Uint8Array,
  options?: ProfileToMdOptions,
): string =>
  speedscopeProfileToMdInternal(parseSpeedscopeProfile(data), options)

export const speedscopeProfileToMdInternal = (
  file: SpeedscopeProfile,
  options?: ProfileToMdOptions,
): string => {
  const normalizedOptions = normalizeSpeedscopeToMdOptions(options)
  return summarizeSpeedscopeProfile(file, normalizedOptions)
    .map(profile => formatSpeedscope(profile, normalizedOptions))
    .join(`\n\n---\n\n`)
}

export { defaultIncludeSpeedscopeEntry } from './common.ts'
