import type { Format } from '../formats/index.ts'
import type { DeepReadonly } from '../helpers/types.ts'
import { fileReferencePath } from '../location.ts'
import type { SourceLocation } from '../location.ts'
import type { EntryCategory, ProfileEntry } from '../options.ts'

/** The context an {@link OriginSpec.matches} predicate inspects. */
export type OriginMatchContext = {
  /** The resolved format of the profile or snapshot being detected. */
  format: Format

  /**
   * The aggregated entries (profile functions, or snapshot constructors and
   * closures) of the profile or snapshot being detected.
   *
   * Predicates should iterate lazily and early-exit on the first discriminating
   * entry to stay roughly `O(1)` amortized.
   */
  entries: readonly DeepReadonly<ProfileEntry>[]
}

/**
 * The internal spec of an origin: a **distinct profiler**, a profiling
 * tool paired with the runtime it observed (e.g. `node` for Node's native V8
 * profiler, `node-pprof` for the `pprof` npm package, `py-spy`, `jvm` for JFR
 * producers).
 *
 * ## What an origin is for
 *
 * An origin drives the categorization rules (which frames are `stdlib`,
 * `third-party`, etc.) that a profile's data implies but doesn't state. Users
 * never see it, only the {@link Origin} ID and the categorization built on it
 *
 * An origin is orthogonal to the {@link Format} (the file type) and the
 * language: several origins emit one format (node, deno, and bun emit V8 CPU
 * profiles; node-pprof and pprof-rs emit pprof), and one language spans several
 * origins (JavaScript spans node, node-pprof, deno, bun, safari).
 *
 * ## When a profiler deserves its own origin
 *
 * Add a new origin only when a profiler leaves a fingerprint **in the frame
 * data** (names or locations, not file-level metadata) that needs a
 * **profiler-specific categorization rule** the existing origins' rules would
 * get wrong. Two tests, both required:
 *
 * 1. **It changes categorization.** If two profilers' frames categorize
 *    identically, one origin covers both. async-profiler and the JDK's Flight
 *    Recorder emit nearly identical JFR so a single `jvm` origin serves both.
 *    They differ only in recording metadata, which categorization never reads,
 *    so distinguishing them buys nothing.
 * 2. **The fingerprint is in the frames.** Detection sees only
 *    {@link OriginMatchContext} entries, and categorization sees only one
 *    entry, so a metadata-only difference is neither detectable nor
 *    categorizable here. The `pprof` npm package qualifies because it names its
 *    garbage-collection frame differently than Node's native one
 *    (`(garbage collector)`), a frame name needing its own rule.
 *
 * Name the origin after the **specific profiler** you have evidence for (e.g.
 * `pprof-rs`, not `rust`). Widen to a runtime/language scope only when
 * *multiple* profilers share the categorization (as the JFR producers do under
 * `jvm`). When a runtime has a builtin profiler, the runtime name doubles as
 * the profiler name (`node`, `deno`, `bun`, `safari`).
 *
 * A profiler that emits an existing format but adds nothing categorization
 * relevant needs no origin: it resolves to an existing origin or the `unknown`
 * fallback.
 */
export type OriginSpec = {
  /** A unique ID for this origin. */
  id: string

  /**
   * The language ID (a key of the `languages` map in `../cli/languages.ts`)
   * this origin's profiles are written in, or `null` for format-generic origins
   * that span languages.
   */
  language: string | null

  /** The formats this origin can emit, used to narrow detection candidates. */
  formats: Format[]

  /**
   * Returns whether the profile or snapshot described by {@link context} was
   * generated by this origin, rather than something that resembles it by
   * coincidence.
   *
   * Match on the profile's **data** (frame names and locations), never its
   * format: a profile can be converted between formats but keeps its original
   * profiler's fingerprints. The format only narrows which origins are tried,
   * and is the fallback when no data signal matches.
   *
   * Only drives origin auto-detection (and is skipped when the user forces an
   * origin), so it should be strict to avoid false positives.
   */
  matches: (context: OriginMatchContext) => boolean

  /**
   * Returns the category of {@link entry} under this origin's runtime
   * conventions: which module specifiers denote builtins (`stdlib`) versus
   * external dependencies (`third-party`), the profiler's synthetic frame
   * names, and so on.
   */
  categorize: (entry: DeepReadonly<ProfileEntry>) => EntryCategory
}

/** Returns whether any entry satisfies {@link predicate}, early-exiting. */
export const someEntry = (
  { entries }: OriginMatchContext,
  predicate: (entry: DeepReadonly<ProfileEntry>) => boolean,
): boolean => {
  for (const entry of entries) {
    if (predicate(entry)) {
      return true
    }
  }
  return false
}

/**
 * Returns whether {@link location} is an absolute URL with one of
 * {@link protocols}.
 */
export const hasProtocol = (
  location: DeepReadonly<SourceLocation> | undefined,
  protocols: string[],
): boolean =>
  location?.type === `absolute` && protocols.includes(location.url.protocol)

/**
 * Returns whether {@link location}'s path lies within a `node_modules/`
 * directory.
 */
export const hasNodeModulesPath = (
  location: DeepReadonly<SourceLocation> | undefined,
): boolean => {
  if (!location) {
    return false
  }
  const path = fileReferencePath(location)
  return path.startsWith(`node_modules/`) || path.includes(`/node_modules/`)
}
