#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
cli_path="$script_dir/../src/cli/index.ts"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT


node \
  --cpu-prof \
  --cpu-prof-interval=50 \
  --diagnostic-dir="$tmpdir" \
  "$cli_path" "$@" > /dev/null

cpuprofile="$(echo "$tmpdir"/*.cpuprofile)"
node "$cli_path" "$cpuprofile"
