#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

node \
  --cpu-prof \
  --cpu-prof-interval=100 \
  --diagnostic-dir="$tmpdir" \
  --input-type=module -e "
    for (let i = 0; i < 10; i++) {
      await import(\`${script_dir}/../src/cli.ts?\${i}\`)
    }
  " -- "$script_dir/bench.js" "$@" > /dev/null

cpuprofile="$(echo "$tmpdir"/*.cpuprofile)"
node "$script_dir/../src/cli.ts" "$cpuprofile"
