import type { ProfileToMdOptions } from '../../common.ts'
import { normalizePprofToMdOptions } from './common.ts'
import { formatPprof } from './format.ts'
import { parsePprof } from './parse.ts'
import { summarizePprof } from './summarize.ts'

/**
 * Converts the given pprof to Markdown.
 *
 * It is assumed that {@link data} is a valid pprof (raw protobuf). The behavior
 * of this function is undefined for invalid profiles.
 *
 * pprof can be generated by many tools, including:
 * - Go's [`runtime/pprof`](https://pkg.go.dev/runtime/pprof) package
 * - Node.js's [`pprof`](https://www.npmjs.com/package/pprof) npm package
 * - Python's [`py-spy`](https://github.com/benfred/py-spy)
 * - Rust's [`pprof-rs`](https://github.com/tikv/pprof-rs)
 */
export const pprofToMd = (
  data: Buffer,
  options?: ProfileToMdOptions,
): string => {
  const normalizedOptions = normalizePprofToMdOptions(options)
  const rawProfile = parsePprof(data)
  const profile = summarizePprof(rawProfile, normalizedOptions)
  return formatPprof(profile, normalizedOptions)
}
